/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AuthenticatedPanelIndexRouteImport } from './routes/_authenticated/panel.index'
import { Route as AuthenticatedPanelAgendaRouteImport } from './routes/_authenticated/panel.agenda'
import { Route as AuthenticatedPanelCompletarRouteImport } from './routes/_authenticated/panel.completar'
import { Route as AuthenticatedPanelConfiguracionRouteImport } from './routes/_authenticated/panel.configuracion'
import { Route as AuthenticatedPanelInventarioRouteImport } from './routes/_authenticated/panel.inventario'
import { Route as AuthenticatedPanelMascotasRouteImport } from './routes/_authenticated/panel.mascotas'
import { Route as AuthenticatedPanelPermisosRouteImport } from './routes/_authenticated/panel.permisos'
import { Route as AuthenticatedPanelPersonalRouteImport } from './routes/_authenticated/panel.personal'
import { Route as AuthenticatedPanelPreciosRouteImport } from './routes/_authenticated/panel.precios'
import { Route as AuthenticatedPanelPropietariosRouteImport } from './routes/_authenticated/panel.propietarios'
import { Route as AuthenticatedPanelRazasRouteImport } from './routes/_authenticated/panel.razas'
import { Route as AuthenticatedPanelReportesRouteImport } from './routes/_authenticated/panel.reportes'
import { Route as AuthenticatedPanelVentasRouteImport } from './routes/_authenticated/panel.ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelIndexRoute = AuthenticatedPanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelAgendaRoute =
  AuthenticatedPanelAgendaRouteImport.update({
    id: '/panel/agenda',
    path: '/panel/agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelCompletarRoute =
  AuthenticatedPanelCompletarRouteImport.update({
    id: '/panel/completar',
    path: '/panel/completar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelConfiguracionRoute =
  AuthenticatedPanelConfiguracionRouteImport.update({
    id: '/panel/configuracion',
    path: '/panel/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelInventarioRoute =
  AuthenticatedPanelInventarioRouteImport.update({
    id: '/panel/inventario',
    path: '/panel/inventario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelMascotasRoute =
  AuthenticatedPanelMascotasRouteImport.update({
    id: '/panel/mascotas',
    path: '/panel/mascotas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelPermisosRoute =
  AuthenticatedPanelPermisosRouteImport.update({
    id: '/panel/permisos',
    path: '/panel/permisos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelPersonalRoute =
  AuthenticatedPanelPersonalRouteImport.update({
    id: '/panel/personal',
    path: '/panel/personal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelPreciosRoute =
  AuthenticatedPanelPreciosRouteImport.update({
    id: '/panel/precios',
    path: '/panel/precios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelPropietariosRoute =
  AuthenticatedPanelPropietariosRouteImport.update({
    id: '/panel/propietarios',
    path: '/panel/propietarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRazasRoute = AuthenticatedPanelRazasRouteImport.update({
  id: '/panel/razas',
  path: '/panel/razas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelReportesRoute =
  AuthenticatedPanelReportesRouteImport.update({
    id: '/panel/reportes',
    path: '/panel/reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelVentasRoute =
  AuthenticatedPanelVentasRouteImport.update({
    id: '/panel/ventas',
    path: '/panel/ventas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/panel/agenda': typeof AuthenticatedPanelAgendaRoute
  '/panel/completar': typeof AuthenticatedPanelCompletarRoute
  '/panel/configuracion': typeof AuthenticatedPanelConfiguracionRoute
  '/panel/inventario': typeof AuthenticatedPanelInventarioRoute
  '/panel/mascotas': typeof AuthenticatedPanelMascotasRoute
  '/panel/permisos': typeof AuthenticatedPanelPermisosRoute
  '/panel/personal': typeof AuthenticatedPanelPersonalRoute
  '/panel/precios': typeof AuthenticatedPanelPreciosRoute
  '/panel/propietarios': typeof AuthenticatedPanelPropietariosRoute
  '/panel/razas': typeof AuthenticatedPanelRazasRoute
  '/panel/reportes': typeof AuthenticatedPanelReportesRoute
  '/panel/ventas': typeof AuthenticatedPanelVentasRoute
  '/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/panel/agenda': typeof AuthenticatedPanelAgendaRoute
  '/panel/completar': typeof AuthenticatedPanelCompletarRoute
  '/panel/configuracion': typeof AuthenticatedPanelConfiguracionRoute
  '/panel/inventario': typeof AuthenticatedPanelInventarioRoute
  '/panel/mascotas': typeof AuthenticatedPanelMascotasRoute
  '/panel/permisos': typeof AuthenticatedPanelPermisosRoute
  '/panel/personal': typeof AuthenticatedPanelPersonalRoute
  '/panel/precios': typeof AuthenticatedPanelPreciosRoute
  '/panel/propietarios': typeof AuthenticatedPanelPropietariosRoute
  '/panel/razas': typeof AuthenticatedPanelRazasRoute
  '/panel/reportes': typeof AuthenticatedPanelReportesRoute
  '/panel/ventas': typeof AuthenticatedPanelVentasRoute
  '/panel': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/panel/agenda': typeof AuthenticatedPanelAgendaRoute
  '/_authenticated/panel/completar': typeof AuthenticatedPanelCompletarRoute
  '/_authenticated/panel/configuracion': typeof AuthenticatedPanelConfiguracionRoute
  '/_authenticated/panel/inventario': typeof AuthenticatedPanelInventarioRoute
  '/_authenticated/panel/mascotas': typeof AuthenticatedPanelMascotasRoute
  '/_authenticated/panel/permisos': typeof AuthenticatedPanelPermisosRoute
  '/_authenticated/panel/personal': typeof AuthenticatedPanelPersonalRoute
  '/_authenticated/panel/precios': typeof AuthenticatedPanelPreciosRoute
  '/_authenticated/panel/propietarios': typeof AuthenticatedPanelPropietariosRoute
  '/_authenticated/panel/razas': typeof AuthenticatedPanelRazasRoute
  '/_authenticated/panel/reportes': typeof AuthenticatedPanelReportesRoute
  '/_authenticated/panel/ventas': typeof AuthenticatedPanelVentasRoute
  '/_authenticated/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/privacidad'
    | '/terminos'
    | '/panel/agenda'
    | '/panel/completar'
    | '/panel/configuracion'
    | '/panel/inventario'
    | '/panel/mascotas'
    | '/panel/permisos'
    | '/panel/personal'
    | '/panel/precios'
    | '/panel/propietarios'
    | '/panel/razas'
    | '/panel/reportes'
    | '/panel/ventas'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/privacidad'
    | '/terminos'
    | '/panel/agenda'
    | '/panel/completar'
    | '/panel/configuracion'
    | '/panel/inventario'
    | '/panel/mascotas'
    | '/panel/permisos'
    | '/panel/personal'
    | '/panel/precios'
    | '/panel/propietarios'
    | '/panel/razas'
    | '/panel/reportes'
    | '/panel/ventas'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/home'
    | '/privacidad'
    | '/terminos'
    | '/_authenticated/panel/agenda'
    | '/_authenticated/panel/completar'
    | '/_authenticated/panel/configuracion'
    | '/_authenticated/panel/inventario'
    | '/_authenticated/panel/mascotas'
    | '/_authenticated/panel/permisos'
    | '/_authenticated/panel/personal'
    | '/_authenticated/panel/precios'
    | '/_authenticated/panel/propietarios'
    | '/_authenticated/panel/razas'
    | '/_authenticated/panel/reportes'
    | '/_authenticated/panel/ventas'
    | '/_authenticated/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel/': {
      id: '/_authenticated/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof AuthenticatedPanelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/agenda': {
      id: '/_authenticated/panel/agenda'
      path: '/panel/agenda'
      fullPath: '/panel/agenda'
      preLoaderRoute: typeof AuthenticatedPanelAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/completar': {
      id: '/_authenticated/panel/completar'
      path: '/panel/completar'
      fullPath: '/panel/completar'
      preLoaderRoute: typeof AuthenticatedPanelCompletarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/configuracion': {
      id: '/_authenticated/panel/configuracion'
      path: '/panel/configuracion'
      fullPath: '/panel/configuracion'
      preLoaderRoute: typeof AuthenticatedPanelConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/inventario': {
      id: '/_authenticated/panel/inventario'
      path: '/panel/inventario'
      fullPath: '/panel/inventario'
      preLoaderRoute: typeof AuthenticatedPanelInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/mascotas': {
      id: '/_authenticated/panel/mascotas'
      path: '/panel/mascotas'
      fullPath: '/panel/mascotas'
      preLoaderRoute: typeof AuthenticatedPanelMascotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/permisos': {
      id: '/_authenticated/panel/permisos'
      path: '/panel/permisos'
      fullPath: '/panel/permisos'
      preLoaderRoute: typeof AuthenticatedPanelPermisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/personal': {
      id: '/_authenticated/panel/personal'
      path: '/panel/personal'
      fullPath: '/panel/personal'
      preLoaderRoute: typeof AuthenticatedPanelPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/precios': {
      id: '/_authenticated/panel/precios'
      path: '/panel/precios'
      fullPath: '/panel/precios'
      preLoaderRoute: typeof AuthenticatedPanelPreciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/propietarios': {
      id: '/_authenticated/panel/propietarios'
      path: '/panel/propietarios'
      fullPath: '/panel/propietarios'
      preLoaderRoute: typeof AuthenticatedPanelPropietariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/razas': {
      id: '/_authenticated/panel/razas'
      path: '/panel/razas'
      fullPath: '/panel/razas'
      preLoaderRoute: typeof AuthenticatedPanelRazasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/reportes': {
      id: '/_authenticated/panel/reportes'
      path: '/panel/reportes'
      fullPath: '/panel/reportes'
      preLoaderRoute: typeof AuthenticatedPanelReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/ventas': {
      id: '/_authenticated/panel/ventas'
      path: '/panel/ventas'
      fullPath: '/panel/ventas'
      preLoaderRoute: typeof AuthenticatedPanelVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelAgendaRoute: typeof AuthenticatedPanelAgendaRoute
  AuthenticatedPanelCompletarRoute: typeof AuthenticatedPanelCompletarRoute
  AuthenticatedPanelConfiguracionRoute: typeof AuthenticatedPanelConfiguracionRoute
  AuthenticatedPanelInventarioRoute: typeof AuthenticatedPanelInventarioRoute
  AuthenticatedPanelMascotasRoute: typeof AuthenticatedPanelMascotasRoute
  AuthenticatedPanelPermisosRoute: typeof AuthenticatedPanelPermisosRoute
  AuthenticatedPanelPersonalRoute: typeof AuthenticatedPanelPersonalRoute
  AuthenticatedPanelPreciosRoute: typeof AuthenticatedPanelPreciosRoute
  AuthenticatedPanelPropietariosRoute: typeof AuthenticatedPanelPropietariosRoute
  AuthenticatedPanelRazasRoute: typeof AuthenticatedPanelRazasRoute
  AuthenticatedPanelReportesRoute: typeof AuthenticatedPanelReportesRoute
  AuthenticatedPanelVentasRoute: typeof AuthenticatedPanelVentasRoute
  AuthenticatedPanelIndexRoute: typeof AuthenticatedPanelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelAgendaRoute: AuthenticatedPanelAgendaRoute,
  AuthenticatedPanelCompletarRoute: AuthenticatedPanelCompletarRoute,
  AuthenticatedPanelConfiguracionRoute: AuthenticatedPanelConfiguracionRoute,
  AuthenticatedPanelInventarioRoute: AuthenticatedPanelInventarioRoute,
  AuthenticatedPanelMascotasRoute: AuthenticatedPanelMascotasRoute,
  AuthenticatedPanelPermisosRoute: AuthenticatedPanelPermisosRoute,
  AuthenticatedPanelPersonalRoute: AuthenticatedPanelPersonalRoute,
  AuthenticatedPanelPreciosRoute: AuthenticatedPanelPreciosRoute,
  AuthenticatedPanelPropietariosRoute: AuthenticatedPanelPropietariosRoute,
  AuthenticatedPanelRazasRoute: AuthenticatedPanelRazasRoute,
  AuthenticatedPanelReportesRoute: AuthenticatedPanelReportesRoute,
  AuthenticatedPanelVentasRoute: AuthenticatedPanelVentasRoute,
  AuthenticatedPanelIndexRoute: AuthenticatedPanelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
